[MODBUS]
Port = '/dev/tnt1'
Baud = 9600
Databits = 8
Parity = 'N'
Time_Out = 250
Sleep = 5000

[PH]
Name = 'PH'
Id = 1
Value_reg = 0
Temp_Reg = 0
Kab_Reg = 0
Enable = true
Retry = 10
Retry_Delay = 100

[COD]
Name = 'COD'
Id = 2
Value_reg = 0
Temp_Reg = 0
Kab_Reg = 0
Enable = true
Retry = 10
Retry_Delay = 100

[NH3N]
Name = 'NH3N'
Id = 3
Value_reg = 0
Temp_Reg = 0
Kab_Reg = 0
Enable = true
Retry = 10
Retry_Delay = 100

[TSS]
Name = 'TSS'
Id = 4
Value_reg = 0
Temp_Reg = 0
Kab_Reg = 0
Enable = true
Retry = 10
Retry_Delay = 100

[FLOW]
Name = 'FLOW'
Id = 5
Value_reg = 0
Temp_Reg = 0
Kab_Reg = 0
Enable = true
Retry = 10
Retry_Delay = 100

[SERVER]
Addr = 'localhost'
Port = '8080'

[DB]
Enable = true
Url = 'postgresql://postgres:123@localhost:5432/sparingdb'
Sleep = 5000
