[MODBUS]
Port = '/dev/tnt1'
Baud = 9600
Databits = 8
Parity = 'N'
Time_Out = 0

[PH]
Name = 'PH'
Id = 1
Value_reg = 0
Temp_Reg = 0
Kab_Reg = 0
Enable = false
Retry = 10
Retry_Delay = 250

[COD]
Name = 'COD'
Id = 2
Value_reg = 0
Temp_Reg = 0
Kab_Reg = 0
Enable = false
Retry = 10
Retry_Delay = 250

[NH3N]
Name = 'NH3N'
Id = 3
Value_reg = 0
Temp_Reg = 0
Kab_Reg = 0
Enable = false
Retry = 10
Retry_Delay = 250

[TSS]
Name = 'TSS'
Id = 4
Value_reg = 0
Temp_Reg = 0
Kab_Reg = 0
Enable = false
Retry = 10
Retry_Delay = 250

[FLOW]
Name = 'FLOW'
Id = 5
Value_reg = 0
Temp_Reg = 0
Kab_Reg = 0
Enable = false
Retry = 10
Retry_Delay = 250

[SERVER]
ADDR = 'localhost'
PORT = '8080'

[DB]
Enable = true
Url = 'postgresql://postgres:123@localhost:5432/sparingdb'

[LOOP]
Reader = 1000
Db = 1000
