[MODBUS]
Port = '/dev/tnt1'
Baud = 9600
Databits = 8
Parity = 'N'
Time_Out = 250
Sleep = 5000

[PH]
Name = 'PH'
Id = 1
Value_reg = 0
Temp_Reg = 2
Kab_Reg = 0
Enable = true
Retry = 10
Retry_Delay = 100
Offset_a = 1.0
Offset_b = 0.0
Min = 4.0
Max = 10.0
Rand_fact = 0.5

[COD]
Name = 'COD'
Id = 2
Value_reg = 0
Temp_Reg = 0
Kab_Reg = 0
Enable = true
Retry = 10
Retry_Delay = 100
Offset_a = 1.0
Offset_b = 0.0
Min = 0.0
Max = 150.0
Rand_fact = 1.0

[NH3N]
Name = 'NH3N'
Id = 3
Value_reg = 0
Temp_Reg = 0
Kab_Reg = 0
Enable = true
Retry = 10
Retry_Delay = 100
Offset_a = 1.0
Offset_b = 0.0
Min = 0.15
Max = 10.0
Rand_fact = 0.1

[TSS]
Name = 'TSS'
Id = 4
Value_reg = 0
Temp_Reg = 0
Kab_Reg = 0
Enable = true
Retry = 10
Retry_Delay = 100
Offset_a = 1.0
Offset_b = 0.0
Min = 0.0
Max = 100.0
Rand_fact = 1.0

[FLOW]
Name = 'FLOW'
Id = 5
Value_reg = 0
Temp_Reg = 0
Kab_Reg = 0
Enable = true
Retry = 10
Retry_Delay = 100
Offset_a = 1.0
Offset_b = 0.0
Min = 0.0
Max = 500.0
Rand_fact = 1.0

[SERVER]
Addr = 'localhost'
Port = '8080'

[DB]
Enable = true
Url = 'postgresql://postgres:123@localhost:5432/sparingdb'
Sleep = 5000
